### ISSUE TITLE
pocket hotline link leads to domain squatter

### ISSUE THREAD

**Issue by imogenkinsman** [ninachaubal/pockethotline#16]
The "powered by pocket hotline" link in the footer leads to a domain squatter (I'm guessing that the domain has expired). We should consider changing the link to lead to the github project for pocket hotline (https://github.com/chap/pockethotline), or simply removing it.

**Comment by sarahmaeve** [comment]
Definitely can remove this.

**Comment by imogenkinsman** [comment]
Sounds good, I'll make a PR later today.
